import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
export default function Home() {
  return (
    <div className="p-2 bg-primary font-main">
      <Head>
        <title>Myself and My Moves - Everything about Dance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mmm-icon.jpg" />
      </Head>

      <main className="min-h-screen min-w-max flex justify-center ">
        <Image src='/images/WEBSITE-back-scaled.jpg' alt='bg-image' layout='fill'/>
        <Navbar />
      </main>

      <footer className='text-primary'>
        <div className="p-4 bg-footer-start grid grid-cols-3 gap-2 h-80 justify-center align-middle items-center justify-items-center ">
          <div className="p-2 flex flex-col w-84">
            <div className='w-44 mb-6'>
            <Image src='/images/mmm-logo-footer.png' alt='footer-logo' width={120} height={50}/>
            </div>
            <p>Where dance education meets fun</p>
          </div>
          <div className="p-2 flex flex-col w-84">
            <h2>Quick Links</h2>
          </div>
          <div className="p-2 flex flex-col w-84">
          <h2>Contact Info</h2>
          </div>
        </div>
        <div className="bg-footer-end h-24"></div>

      </footer >
    </div >
  )
}
